# -*- coding: utf-8 -*-
"""Data_Prep_Kit_Demo (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rInGUfsgxKNmiRsRsMOb3lZ6PrzuBxmM

The following notebook example will allow you to test DPK, without cloning the repo. You can run it either on Google Colab or you can use your local environment (by downloading just the notebook). We use a temporary folder for input and output, but users are encouraged to use their own input folder.
"""

#from google.colab import drive
#drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install "data-prep-toolkit-transforms[pdf2parquet]==1.0.0a2"
# !pip install pandas
# import urllib.request
# import shutil

shutil.os.makedirs("tmp/input", exist_ok=True)
urllib.request.urlretrieve("https://raw.githubusercontent.com/data-prep-kit/data-prep-kit/dev/transforms/language/docling2parquet/test-data/input/archive1.zip", "tmp/input/archive1.zip")
urllib.request.urlretrieve("https://raw.githubusercontent.com/data-prep-kit/data-prep-kit/dev/transforms/language/docling2parquet/test-data/input/redp5110-ch1.pdf", "tmp/input/redp5110-ch1.pdf")

!pip install --upgrade numpy
!pip install --upgrade pandas

!pip install virtualenv
!virtualenv venv
!source venv/bin/activate
!pip install "data-prep-toolkit-transforms[pdf2parquet]==1.0.0a2" pandas
#Continue with your notebook from here, but ensure you run all installations within the created virtual environment.

from dpk_pdf2parquet.transform_python import Pdf2Parquet
from dpk_pdf2parquet.transform import pdf2parquet_contents_types

Pdf2Parquet(input_folder= "tmp/input",
               output_folder= "tmp/output",
               data_files_to_use=['.pdf', '.zip'],
               pdf2parquet_contents_type=pdf2parquet_contents_types.JSON).transform()

import pyarrow.parquet as pq
import pandas as pd
table = pq.read_table('tmp/output/archive1.parquet')
table.to_pandas()

table = pq.read_table('tmp/output/redp5110-ch1.parquet')
table.to_pandas()

import os

# Print current working directory
print("Current working directory:", os.getcwd())

# List folders in the current directory
print(os.listdir('.'))

# Check if 'tmp' is in the current directory
if 'tmp' in os.listdir('.'):
    print("Contents of tmp:")
    print(os.listdir('tmp'))
    if 'output' in os.listdir('tmp'):
        print("Contents of tmp/output:")
        print(os.listdir('tmp/output'))

# Search for the parquet file recursively
for root, dirs, files in os.walk('.'):
    for file in files:
        if file.endswith('archive1.parquet'):
            print("Found:", os.path.join(root, file))

#Use Shell Commands to Search(optional)
!find . -name "archive1.parquet"

